### ISSUE TITLE
Improved Typescript Support

### ISSUE THREAD

**Issue by dustinlacewell** [disunity-hq/store#1]
This will involve making it easier to couple some TypeScript to a given page on the frontend.

A rough outline of the steps:

- [ ] Create a `pages/` section in the typescript sources
- [ ] Have webpack crawl the `pages/` directory for source files
- [ ] Make a webpack entrypoint for each discovered page source file
- [ ] Make a webpack output for each discovered page source file
- [ ] Make an ASP TagHelper allowing us to easily specify a page TS source file

The TagHelper should take a pseudo path like "mods/upload" and try to resolve the corresponding webpack bundle. It should handle dev/prod un/minified versions.

**Comment by scottbot95** [comment]
We can use the `glob` package do to a wildcard search for something like `pages/**/main.ts`

See https://hackernoon.com/webpack-creating-dynamically-named-outputs-for-wildcarded-entry-files-9241f596b065

**Comment by dustinlacewell** [comment]
This was completed in https://github.com/disunity-hq/store/commit/dfc713da821165ffbecb435c49f4e266e96e4fd8 and https://github.com/disunity-hq/store/commit/80ad3d80849e4e20680f260c369f0ddc2dcae051
