### ISSUE TITLE
Update DisplayName when uploading latest version

### ISSUE THREAD

**Issue by dustinlacewell** [disunity-hq/store#22]
Currently `Mod.DisplayName` is set when the first `ModVersion` for a `Mod` is created. 

We should update the `Mod.DisplayName` when the `ModVersion` being created also happens to be the latest version for the associated `Mod`. 

In other words, uploading a mod should update the mod's name if the version is the newest.

_Alternatively_, make `Mod.DisplayName` simply proxy `Latest.DisplayName`

**Comment by scottbot95** [comment]
I have removed `DisplayName` in lieu of having it proxy to the latest version from `Mod`s and `Target`s as it was causing problems with EF Core.
